#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:1
#SBATCH --gres-flags=enforce-binding
#SBATCH --time=144:00:00
#SBATCH -J FEP-rest
#SBATCH -p gpu-biggin4
#SBATCH --array=1-12

wd=$PWD

source /etc/profile.d/modules.sh
module load use.own
module load local-apps/gromacs/2021.1-AVX2

setup_dir="${PWD}/../final-topology/"

let index=${SLURM_ARRAY_TASK_ID}-1

cd restraints.${index}
  # Set up directory
  sub_wd=$PWD
  cd prod
    gmx mdrun -v -deffnm prod -ntmpi 1 -ntomp 6 2>&1 | tee run.log
    cd $wd

wait
